<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

        <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/spotify/search">
              <span data-feather="home"></span>
              Search
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/user/dashboard">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          
        
    
        

      </div>
    </nav>